language: python
python:
    - "2.7"
before_install:
    - apt-get update
    - apt-get install -y python-pygame
install: "pip install -r requirements.txt"
script: "nosetests -w tests --with-coverage --cover-package=pin"
sudo: required
